#!/bin/sh

PATH=/bin:/bin/applets
export PATH
/bin/busybox --install -s /bin/applets/

dmesg -n 1

mkdir -pv /dev /proc /sys
mkdir -pv -m 1777 /tmp 

echo "Mounting /dev"
mountpoint -q /dev || mount -t devtmpfs none /dev

echo "Mounting /proc"
mountpoint -q /proc || mount -t proc none /proc

echo "Mounting /sys"
mountpoint -q /sys || mount -t sysfs none /sys


if [ -z `grep -o rescue /proc/cmdline` ]; then
  echo "Executing /rc.init"
  . /rc.init
else
 echo "RESCUE MODE: Dropping to shell"
 exec setsid cttyhack sh
fi
