#!/bin/busybox echo "This file is sourced from /init"

distro=${distro}
live=${live}
echo live=${live}
echo distro=${distro}

if [ ! -z "$live" ]; then
   echo "Mounting live media"
   mount $(findfs ${live}) /live
fi

if [ -r /live/${distro}/boot/autostart.sh ]; then
  echo Executing /live/${distro}/boot/autostart.sh
   . /live/${distro}/boot/autostart.sh
fi


while true; do
setsid cttyhack /bin/sh
done

