#!/bin/busybox echo "This file is sourced from /init"

distro=${distro}
live=${live}
echo live=${live}
echo distro=${distro}

# If the lenght of the string "$live" is not zero
if [ -n "$live" ]; then
   echo "Mounting live media"
   mkdir -p /live
   mount $(findfs ${live}) /live
fi

if [ -r /live/${distro}/boot/autostart.sh ]; then
  echo Executing /live/${distro}/boot/autostart.sh
   . /live/${distro}/boot/autostart.sh
fi


while true; do
tty -s && /bin/sh || setsid cttyhack /bin/sh
done

